// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3LNQLYmk5p4ivPPaTaq392GGc-50fHxg',
    appId: '1:183281990207:web:c94bcf1dae71a946a3968a',
    messagingSenderId: '183281990207',
    projectId: 'caffee-breeze',
    authDomain: 'caffee-breeze.firebaseapp.com',
    storageBucket: 'caffee-breeze.appspot.com',
    measurementId: 'G-5SDPQR5P79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_7vlxCo7-sbUlS_JO1IqKCZ2fTOto3Vw',
    appId: '1:183281990207:android:9bc3b9ec4efd6e31a3968a',
    messagingSenderId: '183281990207',
    projectId: 'caffee-breeze',
    storageBucket: 'caffee-breeze.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBfj9x1doVchhJqtJBkiZSH7USqa3KBLw',
    appId: '1:183281990207:ios:6f2ee52c817f9454a3968a',
    messagingSenderId: '183281990207',
    projectId: 'caffee-breeze',
    storageBucket: 'caffee-breeze.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBfj9x1doVchhJqtJBkiZSH7USqa3KBLw',
    appId: '1:183281990207:ios:6f2ee52c817f9454a3968a',
    messagingSenderId: '183281990207',
    projectId: 'caffee-breeze',
    storageBucket: 'caffee-breeze.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3LNQLYmk5p4ivPPaTaq392GGc-50fHxg',
    appId: '1:183281990207:web:44ed71bbb40b08b3a3968a',
    messagingSenderId: '183281990207',
    projectId: 'caffee-breeze',
    authDomain: 'caffee-breeze.firebaseapp.com',
    storageBucket: 'caffee-breeze.appspot.com',
    measurementId: 'G-2MPWYEFZWT',
  );
}
